### PR TITLE
Adding bower compatibility

### PR DESCRIPTION
**Pull request by jonatas**
I just add a bower file to allow me to consume these library via [bower package manager](http://bower.io).

Can you register the package and confirm your own information about the project?

### CODE REVIEW

**Comment by mtschirs** [comment]
Looks fine to me, thanks for sharing! I rarely use bower, so could you quickly explain to me whether the values you put into "ignore" are common practice?
 "ignore": [
+    "**/.*",
+    "node_modules",
+    "bower_components",
+    "test",
+    "tests"
+  ]

**Comment by jonatas** [comment]
The ignore is about files will be ignored when installing the package. You can see more details about [ignore here](http://bower.io/docs/creating-packages/#ignore).

**Comment by mtschirs** [comment]
Yes, but since the values in "ignore" do not relate to paths or files within js-objectdetect, wouldn't it make sense to set "ignore": [] ? Or is it common practice to include these values in the ignore array no matter whether they are used by the project or not?

**Comment by jonatas** [comment]
Really true @mtschirs, I think the node_modules and bower_components should be included as dependencies. I believe it will automatically be ignored.

The ignore section was suggested by own `bower init` command. In fact all the file was filled based on the default suggestions from bower.

The test and tests folder really doesn't make sense for that case because these folders doesn't exist.

The .* should be useful to avoid `.git` and `.gitignore`.

I'll push these fixes now.

**Comment by mtschirs** [comment]
hm, actually you are right, I forgot about .gitignore. So I should actually add the "*/." again, right? Anyway, thank you a lot for this useful contribution :+1:

**Comment by jonatas** [comment]
:+1: Thank you for merge it! As soon as started using it, it works fine! I
got four fist hands (me and my soon) identified with success :)

On Thu, Aug 27, 2015 at 11:58 AM, mtschirs <notifications@github.com> wrote:

> hm, actually you are right, I forgot about .gitignore. So I should
> actually add the "*/." again, right? Anyway, thank you a lot for this
> useful contribution [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtschirs/js-objectdetect/pull/24#issuecomment-135460594>
> .
>



-- 
atenciosamente,

Jônatas Davi Paganini.

--
[ *ideia.me <http://ideia.me> **eu* *invent.to <http://invent.to/>* ]
46 9911 7879

**Pull request merged**
